# localhost
@hostname = secure-gorge-62437.herokuapp.com
# 8080
@port = 80
@host = http://{{hostname}}:{{port}}/api
@contentType = application/json

### login
# @name login
POST {{host}}/auth/login
Content-Type: {{contentType}}

{
    "username": "test",
    "password": "test"
}

@authToken = {{login.response.body.jwt}}

### home
GET {{host}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}
